[CmdletBinding()]
param(
    [ValidateSet("ping", "request_state")]
    [string] $Type = "ping",

    [int] $TimeoutSeconds = 45,

    [switch] $LeaveMaxOpen
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = "Stop"

function Resolve-RequiredPath {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Path,

        [Parameter(Mandatory = $true)]
        [string] $Label
    )

    $resolvedPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)
    if (-not (Test-Path -LiteralPath $resolvedPath)) {
        throw "$Label not found: $resolvedPath"
    }
    return $resolvedPath
}

function Convert-ToMaxPath {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Path
    )

    return $Path.Replace("\", "/")
}

function Remove-FileIfPresent {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Path
    )

    if (Test-Path -LiteralPath $Path) {
        Remove-Item -LiteralPath $Path -Force
    }
}

function Get-MissingSmokeOutputs {
    param(
        [Parameter(Mandatory = $true)]
        [string] $CommandType,

        [Parameter(Mandatory = $true)]
        [string] $AckPath,

        [Parameter(Mandatory = $true)]
        [string] $LogPath,

        [Parameter(Mandatory = $true)]
        [string] $StatePath
    )

    $missing = @()
    if (-not (Test-Path -LiteralPath $AckPath)) {
        $missing += "responses/ack.json"
    }
    if (-not (Test-Path -LiteralPath $LogPath)) {
        $missing += "logs/harness-session.jsonl"
    }
    if ($CommandType -eq "request_state" -and -not (Test-Path -LiteralPath $StatePath)) {
        $missing += "state/state.current.json"
    }
    return $missing
}

if ($TimeoutSeconds -lt 1) {
    throw "TimeoutSeconds must be greater than zero."
}

if ([string]::IsNullOrWhiteSpace($env:VESPERARE_MAX_EXE)) {
    throw "VESPERARE_MAX_EXE is not set. Set it to the local Max.exe path before running this smoke script."
}

$maxExe = Resolve-RequiredPath -Path $env:VESPERARE_MAX_EXE -Label "VESPERARE_MAX_EXE"

$repoRoot = Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..\..\..")
$repoRoot = $repoRoot.ProviderPath
if (-not (Test-Path -LiteralPath (Join-Path $repoRoot ".git"))) {
    throw "Repo root verification failed; .git not found under: $repoRoot"
}

$harnessRoot = Join-Path $repoRoot "projects\max\_harness"
$bridgePath = Resolve-RequiredPath -Path (Join-Path $harnessRoot "node\vesperare-harness-bridge-v2.js") -Label "Node for Max bridge"
$commandPath = Join-Path $harnessRoot "commands\command.pending.json"
$ackPath = Join-Path $harnessRoot "responses\ack.json"
$errorPath = Join-Path $harnessRoot "responses\error.json"
$logPath = Join-Path $harnessRoot "logs\harness-session.jsonl"
$statePath = Join-Path $harnessRoot "state\state.current.json"

$newCommandScript = Resolve-RequiredPath -Path (Join-Path $PSScriptRoot "New-VesperareHarnessCommand.ps1") -Label "command writer"
$commandValidatorPath = Resolve-RequiredPath -Path (Join-Path $PSScriptRoot "Test-VesperareHarnessCommand.ps1") -Label "command validator"
$ackValidatorPath = Resolve-RequiredPath -Path (Join-Path $PSScriptRoot "Test-VesperareHarnessAck.ps1") -Label "ack validator"
$errorValidatorPath = Resolve-RequiredPath -Path (Join-Path $PSScriptRoot "Test-VesperareHarnessError.ps1") -Label "error validator"
$logValidatorPath = Resolve-RequiredPath -Path (Join-Path $PSScriptRoot "Test-VesperareHarnessLog.ps1") -Label "log validator"
$stateValidatorPath = Resolve-RequiredPath -Path (Join-Path $PSScriptRoot "Test-VesperareHarnessState.ps1") -Label "state validator"

foreach ($directory in @(
    (Split-Path -Parent $commandPath),
    (Split-Path -Parent $ackPath),
    (Split-Path -Parent $logPath),
    (Split-Path -Parent $statePath)
)) {
    if (-not (Test-Path -LiteralPath $directory)) {
        New-Item -ItemType Directory -Path $directory -Force | Out-Null
    }
}

foreach ($runtimeFile in @($commandPath, $ackPath, $errorPath, $logPath, $statePath)) {
    Remove-FileIfPresent -Path $runtimeFile
}

$runId = "run-max-harness-smoke-" + [guid]::NewGuid().ToString("N")
$commandId = "cmd-max-harness-smoke-$Type-" + [guid]::NewGuid().ToString("N")

& $newCommandScript `
    -OutputPath $commandPath `
    -Type $Type `
    -Target "harness" `
    -Mode "active" `
    -CommandId $commandId `
    -RunId $runId `
    -Notes "Generated by Invoke-VesperareMaxHarnessSmoke.ps1; file-only Max/Codex harness smoke." `
    -Force | Out-Null

& $commandValidatorPath -CommandPath $commandPath | Write-Output

$tmpRoot = Join-Path $repoRoot ".codex_tmp"
if (-not (Test-Path -LiteralPath $tmpRoot)) {
    New-Item -ItemType Directory -Path $tmpRoot -Force | Out-Null
}

$tempPatchPath = Join-Path $tmpRoot "vesperare-max-harness-smoke-node-bridge-v2.maxpat"
$bridgeMaxPath = Convert-ToMaxPath -Path $bridgePath
$bridgeDirMaxPath = Convert-ToMaxPath -Path (Split-Path -Parent $bridgePath)

$patch = [ordered]@{
    patcher = [ordered]@{
        fileversion = 1
        appversion = [ordered]@{
            major = 9
            minor = 0
            revision = 0
            architecture = "x64"
            modernui = 1
        }
        classnamespace = "box"
        rect = @(120.0, 120.0, 940.0, 420.0)
        bglocked = 0
        openinpresentation = 0
        default_fontsize = 12.0
        default_fontface = 0
        default_fontname = "Arial"
        gridonopen = 1
        gridsize = @(15.0, 15.0)
        gridsnaponopen = 1
        objectsnaponopen = 1
        statusbarvisible = 2
        toolbarvisible = 1
        lefttoolbarpinned = 0
        toptoolbarpinned = 0
        righttoolbarpinned = 0
        bottomtoolbarpinned = 0
        toolbars_unpinned_last_save = 0
        tallnewobj = 0
        boxanimatetime = 200
        enablehscroll = 1
        enablevscroll = 1
        devicewidth = 0.0
        description = ""
        digest = ""
        tags = ""
        style = ""
        subpatcher_template = ""
        assistshowspatchername = 0
        boxes = @(
            [ordered]@{
                box = [ordered]@{
                    id = "obj-1"
                    maxclass = "comment"
                    numinlets = 1
                    numoutlets = 0
                    patching_rect = @(30.0, 25.0, 820.0, 20.0)
                    text = "Temporary Vesperare harness smoke patch generated under .codex_tmp. It does not open, read, modify or validate patch 01."
                }
            },
            [ordered]@{
                box = [ordered]@{
                    id = "obj-2"
                    maxclass = "comment"
                    numinlets = 1
                    numoutlets = 0
                    patching_rect = @(30.0, 55.0, 820.0, 36.0)
                    text = "Scope: start one node.script bridge by absolute local path and write only harness ack/error/log/state files."
                }
            },
            [ordered]@{
                box = [ordered]@{
                    id = "obj-3"
                    maxclass = "newobj"
                    numinlets = 1
                    numoutlets = 2
                    outlettype = @("", "")
                    patching_rect = @(45.0, 160.0, 790.0, 22.0)
                    saved_object_attributes = [ordered]@{
                        autostart = 1
                        defer = 0
                        watch = 0
                    }
                    text = "node.script $bridgeMaxPath @autostart 1 @watch 0"
                    textfile = [ordered]@{
                        filename = $bridgeMaxPath
                        flags = 0
                        embed = 0
                        autowatch = 0
                    }
                }
            }
        )
        lines = @()
        dependency_cache = @(
            [ordered]@{
                name = "vesperare-harness-bridge-v2.js"
                bootpath = $bridgeDirMaxPath
                patcherrelativepath = "../node"
                type = "TEXT"
                implicit = 1
            }
        )
        autosave = 0
    }
}

$patch | ConvertTo-Json -Depth 64 | Set-Content -LiteralPath $tempPatchPath -Encoding UTF8
Get-Content -LiteralPath $tempPatchPath -Raw | ConvertFrom-Json | Out-Null
Write-Output "OK: temporary Max patch JSON parsed from $tempPatchPath"

$maxProcess = $null
try {
    $maxProcess = Start-Process -FilePath $maxExe -ArgumentList "`"$tempPatchPath`"" -PassThru -WindowStyle Hidden
    Write-Output "OK: Max launched for harness smoke with PID $($maxProcess.Id)"

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    do {
        if (Test-Path -LiteralPath $errorPath) {
            break
        }

        $missing = @(Get-MissingSmokeOutputs -CommandType $Type -AckPath $ackPath -LogPath $logPath -StatePath $statePath)
        if ($missing.Count -eq 0) {
            break
        }

        Start-Sleep -Milliseconds 500
    } while ((Get-Date) -lt $deadline)

    if (Test-Path -LiteralPath $errorPath) {
        & $errorValidatorPath -ErrorPath $errorPath | Write-Output
        throw "Max harness smoke produced error.json instead of ack output: $errorPath"
    }

    $missing = @(Get-MissingSmokeOutputs -CommandType $Type -AckPath $ackPath -LogPath $logPath -StatePath $statePath)
    if ($missing.Count -gt 0) {
        throw "Timed out after $TimeoutSeconds second(s). Missing output(s): $($missing -join ', ')"
    }

    & $ackValidatorPath -AckPath $ackPath | Write-Output
    & $logValidatorPath -LogPath $logPath | Write-Output
    if ($Type -eq "request_state") {
        & $stateValidatorPath -StatePath $statePath | Write-Output
    }

    Write-Output "OK: Max harness smoke '$Type' completed for run_id $runId"
}
finally {
    if (-not $LeaveMaxOpen -and $null -ne $maxProcess) {
        $process = Get-Process -Id $maxProcess.Id -ErrorAction SilentlyContinue
        if ($null -ne $process) {
            Stop-Process -Id $maxProcess.Id -Force -ErrorAction SilentlyContinue
            Write-Output "OK: stopped Max process PID $($maxProcess.Id)"
        }
    }
}
